application: myapp
version: 1
runtime: python
api_version: 1

handlers:  
- url: /favicon.ico
  static_files: application/static/favicon.ico
  upload: application/static/favicon.ico
  
- url: /robots.txt
  static_files: application/static/robots.txt
  upload: application/static/robots.txt
  
- url: /static
  static_dir: application/static
  secure: never

- url: .*
  script: main.py
